# Generated by Django 3.0.3 on 2020-02-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='pics')),
                ('stock', models.ImageField(default=0, upload_to='')),
            ],
        ),
    ]
