# Generated by Django 3.0.3 on 2020-02-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozi_components_datasheet', '0002_auto_20200206_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
    ]
