# Generated by Django 3.0.3 on 2020-02-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozi_components_datasheet', '0004_transactionlist_transactionlist1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlist',
            name='wid_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transactionlist1',
            name='wid_time',
            field=models.DateTimeField(),
        ),
    ]
