# Generated by Django 3.0.3 on 2020-02-22 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozi_components_datasheet', '0006_auto_20200211_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlist',
            name='wid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 11, 8, 37, 216241)),
        ),
        migrations.AlterField(
            model_name='transactionlist1',
            name='wid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 11, 8, 37, 217722)),
        ),
    ]
